var searchData=
[
  ['va_5flist',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['valid',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()'],['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()']]],
  ['value',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()']]],
  ['value_5fcomp',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()']]],
  ['value_5fcompare',['value_compare',['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap::value_compare'],['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map::value_compare']]],
  ['value_5for',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional::value_or(T... args)'],['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional::value_or(T... args)']]],
  ['valuesgenerator',['ValuesGenerator',['../class_catch_1_1_values_generator.html',1,'Catch']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::vector'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector(T... args)'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector(T... args)']]],
  ['vector_3c_20catch_3a_3aptr_3c_20catch_3a_3amatchers_3a_3aimpl_3a_3amatcher_3c_20expressiont_20_3e_20_3e_20_3e',['vector&lt; Catch::Ptr&lt; Catch::Matchers::Impl::Matcher&lt; ExpressionT &gt; &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20const_20catch_3a_3aigenerator_3c_20t_20_3e_20_2a_3e',['vector&lt; const Catch::IGenerator&lt; T &gt; *&gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20score_20_3e',['vector&lt; Score &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20case_20_3e_20_3e',['vector&lt; std::vector&lt; Case &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20t_20_3e',['vector&lt; T &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vfprintf',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['view',['View',['../class_view.html',1,'View'],['../class_view.html#a7c91b725a55a7843fc628e29d85f53a2',1,'View::View(Game *game)'],['../class_view.html#a44ad60a768422d3fa8fbd7576950080a',1,'View::View()']]],
  ['vprintf',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
